name: Go Mod Tidy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tidy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Go 环境
        uses: actions/setup-go@v2
        with:
          go-version: '^1.23.4'

      - name: 执行 go mod tidy
        shell: bash
        run: |
          # 查找所有包含 go.mod 的子目录并执行 go mod tidy
          find . -name 'go.mod' -execdir go mod tidy \;

      - name: 配置 Git 用户信息
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: "chore: auto run go mod tidy"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
